{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: {{ .Values.ingress.name }}
    labels:
        app.kubernetes.io/name: {{ .Values.ingress.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: clearml-server
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/version: {{ .Values.clearml.image.tag }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    {{- with .Values.ingress.annotations }}
    annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

spec:
  tls:
    - hosts:
        - "app.{{ .Values.ingress.host }}"
        - "files.{{ .Values.ingress.host }}"
        - "api.{{ .Values.ingress.host }}"
        {{- if .Values.ingress.tls.secretName }}
      secretName: {{ .Values.ingress.tls.secretName }}
        {{- end }}
  rules:
    - host: "app.{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: webserver-service
              servicePort: 80
    - host: "api.{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: apiserver-service
              servicePort: 8008
    - host: "files.{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: fileserver-service
              servicePort: 8081
{{- end }}
