apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.mongo.name}}
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: clearml-server
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  namespace: {{ .Values.clearml.namespace }}
spec:
  selector:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: clearml-server
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: clearml-server
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: mongo
  namespace: {{ .Values.clearml.namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mongo
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/part-of: clearml-server
      app.kubernetes.io/managed-by: {{ .Release.Service }}
  minReadySeconds: 20
  progressDeadlineSeconds: 30
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongo
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: clearml-server
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - clearml
      containers:
      - image: mongo:3.6.5
        name: mongo
        args: ["--setParameter", "internalQueryExecMaxBlockingSortBytes=196100200"]
        resources:
          requests:
            memory: "125M"
            cpu: "200m"
          limits:
            memory: "250M"
            cpu: "300m"
        volumeMounts:
        - mountPath: /data/db
          name: mongo-hostpath0
        - mountPath: /data/configdb
          name: mongo-hostpath1
      restartPolicy: Always
      nodeSelector:
        {{ .Values.clearml.nodeSelector}}
      volumes:
      - name: mongo-hostpath0
        persistentVolumeClaim:
          claimName: mongo-pv-claim0
      - name: mongo-hostpath1
        persistentVolumeClaim:
          claimName: mongo-pv-claim1
