apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: agentservices
    app.kubernetes.io/instance: clearml-server
    app.kubernetes.io/part-of: clearml-server
  name: agent-services
  namespace: clearml
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: agentservices
      app.kubernetes.io/instance: clearml-server
      app.kubernetes.io/part-of: clearml-server
  minReadySeconds: 20
  progressDeadlineSeconds: 30
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: agentservices
        app.kubernetes.io/instance: clearml-server
        app.kubernetes.io/part-of: clearml-server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - clearml
      containers:
      - image: allegroai/clearml-agent-services:latest
        imagePullPolicy: Always
        name: agentservices
        env:
        - name: CLEARML_API_HOST
          value: "http://apiserver-service:8008"
        - name: CLEARML_AGENT_DEFAULT_BASE_DOCKER
          value: "ubuntu:18.04"
        - name: CLEARML_WORKER_ID
          value: "clearml-services"
        - name: CLEARML_AGENT_DOCKER_HOST_MOUNT
          value: "/opt/clearml/agent:/root/.clearml"
        #  Fill in the following in order set the values for clearml-agent:
        # - name: CLEARML_HOST_IP
        #   value: ""
        # - name: CLEARML_WEB_HOST
        #   value: ""
        # - name: CLEARML_FILES_HOST
        #   value: ""
        # - name: CLEARML_API_ACCESS_KEY
        #   value: ""
        # - name: CLEARML_API_SECRET_KEY
        #   value: ""
        # - name: CLEARML_AGENT_GIT_USER
        #   value: ""
        # - name: CLEARML_AGENT_GIT_PASS
        #   value: ""
        # - name: CLEARML_AGENT_UPDATE_VERSION
        #   value: ""
        # - name: AWS_ACCESS_KEY_ID
        #   value: ""
        # - name: AWS_SECRET_ACCESS_KEY
        #   value: ""
        # - name: AWS_DEFAULT_REGION
        #   value: ""
        # - name: AZURE_STORAGE_ACCOUNT
        #   value: ""
        # - name: AZURE_STORAGE_KEY
        #   value: ""
        # - name: GOOGLE_APPLICATION_CREDENTIALS
        #   value: ""
        args:
        - agentservices
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: dockersock
        - mountPath: /root/.clearml
          name: agent-data
      restartPolicy: Always
      nodeSelector:
        app: clearml
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: agent-data
        hostPath:
          path: /opt/clearml/agent
