apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: apiserver
    app.kubernetes.io/instance: clearml-server
    app.kubernetes.io/part-of: clearml-server
  name: apiserver-service
  namespace: clearml
spec:
  selector:
    app.kubernetes.io/name: apiserver
    app.kubernetes.io/instance: clearml-server
    app.kubernetes.io/part-of: clearml-server
  type: NodePort
  ports:
  - protocol: TCP
    port: 8008
    targetPort: 8008
    nodePort: 30008
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: apiserver
    app.kubernetes.io/instance: clearml-server
    app.kubernetes.io/part-of: clearml-server
  name: apiserver
  namespace: clearml
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: apiserver
      app.kubernetes.io/instance: clearml-server
      app.kubernetes.io/part-of: clearml-server
      clearml: apiserver
      platform: clearml
  minReadySeconds: 20
  progressDeadlineSeconds: 30
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apiserver
        app.kubernetes.io/instance: clearml-server
        app.kubernetes.io/part-of: clearml-server
        clearml: apiserver
        platform: clearml
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - clearml
      containers:
      - image: allegroai/clearml:latest
        imagePullPolicy: Always
        name: apiserver
        resources:
          requests:
            memory: "150M"
            cpu: "200m"
          limits:
            memory: "150M"
            cpu: "400m"
        env:
        - name: TRAINS_ELASTIC_SERVICE_HOST
          value: elasticsearch-service
        - name: TRAINS_ELASTIC_SERVICE_PORT
          value: "9200"
        - name: TRAINS_MONGODB_SERVICE_HOST
          value: mongo-service
        - name: TRAINS_MONGODB_SERVICE_PORT
          value: "27017"
        - name: TRAINS_REDIS_SERVICE_HOST
          value: redis
        - name: TRAINS_REDIS_SERVICE_PORT
          value: "6379"
        - name: TRAINS_SERVER_DEPLOYMENT_TYPE
          value: "k8s"
        - name: TRAINS__apiserver__pre_populate__enabled
          value: "true"
        - name: TRAINS__apiserver__pre_populate__zip_files
          value: "/opt/trains/db-pre-populate"
        - name: TRAINS__apiserver__pre_populate__artifacts_path
          value: "/mnt/fileserver"
        args:
        - apiserver
        volumeMounts:
        - mountPath: /var/log/clearml
          name: apiserver-hostpath0
        - mountPath: /opt/clearml/config
          name: apiserver-hostpath1
      restartPolicy: Always
      nodeSelector:
        app: clearml
      volumes:
      - name: apiserver-hostpath0
        hostPath:
          path: /opt/clearml/logs
      - name: apiserver-hostpath1
        hostPath:
          path: /opt/clearml/config
