apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: webserver
    app.kubernetes.io/instance: clearml-server
    app.kubernetes.io/part-of: clearml-server
  name: webserver-service
  namespace: clearml
spec:
  selector:
    app.kubernetes.io/name: webserver
    app.kubernetes.io/instance: clearml-server
    app.kubernetes.io/part-of: clearml-server
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: webserver
    app.kubernetes.io/instance: clearml-server
    app.kubernetes.io/part-of: clearml-server
  name: webserver
  namespace: clearml
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: webserver
      app.kubernetes.io/instance: clearml-server
      app.kubernetes.io/part-of: clearml-server
  progressDeadlineSeconds: 10
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webserver
        app.kubernetes.io/instance: clearml-server
        app.kubernetes.io/part-of: clearml-server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
                - key: app
                  operator: In
                  values:
                  - clearml
      containers:
      - image: allegroai/clearml:latest
        imagePullPolicy: Always
        name: webserver
        resources:
          requests:
            memory: "25M"
            cpu: "100m"
          limits:
            memory: "50M"
            cpu: "200m"
        args:
        - webserver
        env:
        - name: NGINX_APISERVER_ADDRESS
          value: "http://apiserver-service:8008/"
      restartPolicy: Always
      nodeSelector:
        app: clearml
