apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: fileserver
    app.kubernetes.io/instance: trains-server
    app.kubernetes.io/part-of: trains-server
  name: fileserver-service
  namespace: trains
spec:
  selector:
    app.kubernetes.io/name: fileserver
    app.kubernetes.io/instance: trains-server
    app.kubernetes.io/part-of: trains-server
  type: NodePort
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: fileserver
    app.kubernetes.io/instance: trains-server
    app.kubernetes.io/part-of: trains-server
  name: fileserver
  namespace: trains
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fileserver
      app.kubernetes.io/instance: trains-server
      app.kubernetes.io/part-of: trains-server
  progressDeadlineSeconds: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fileserver
        app.kubernetes.io/instance: trains-server
        app.kubernetes.io/part-of: trains-server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - trains
      containers:
      - image: allegroai/trains-server:0.11.0
        name: fileserver
        resources:
          requests:
            memory: "30M"
            cpu: "50m"
          limits:
            memory: "60M"
            cpu: "100m"
        args:
        - fileserver
        volumeMounts:
        - mountPath: /var/log/trains
          name: fileserver-hostpath0
        - mountPath: /mnt/fileserver
          name: fileserver-hostpath1
      restartPolicy: Always
      nodeSelector:
        app: trains
      volumes:
      - name: fileserver-hostpath0
        hostPath:
          path: /opt/trains/logs
      - name: fileserver-hostpath1
        hostPath:
          path: /opt/trains/data/fileserver
